name: Docker

on:
  push:
    branches: [ develop, master ]
    tags: [ v*.*.* ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: rlespinasse/github-slug-action@v2.x
    - name: Build the project
      run: |
        npm install
        npm run clean
        npm run build
        npm prune --production
    - name: Build Docker image
      run: docker build --tag openeduhub/editor-backend:${{ env.GITHUB_REF_SLUG }} .
    - name: Publish to DockerHub
      run: docker push openeduhub/editor-backend:${{ env.GITHUB_REF_SLUG }}